name: run twitterbot.py


on:
  schedule:
    - cron: '* * * * *' # Every 30 Minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ../../requirements.txt
          
      - name: execute py script # run main.py
        env:
          api_key: ${{secrets.API_KEY}}
          api_secret: ${{secrets.API_SECRET}}
          access_token: ${{secrets.ACCESS_TOKEN}}
          access_token_secret: ${{secrets.ACCESS_TOKEN_SECRET}}
          bearer_token: ${{secrets.BEARER_TOKEN}}
          unsplash_access_key: ${{secrets.UNSPLASH_ACCESS_KEY}}
        run: python main.py
